# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "ahci"
    "xhci_pci"
    "usb_storage"
    "sd_mod"
    "sdhci_pci"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  	# old? mmcblk0p2 e46361e0-b507-412c-a93f-5994dbb7a91c
  	# old? mmcblk0p3 
	# mmcblk0p2 740e97de-230d-458a-b052-159e5fcfdb75
	# mmcblk0p3 fa47f6fa-0c53-46a2-8f7b-e74327ebdc03
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/740e97de-230d-458a-b052-159e5fcfdb75";
    fsType = "btrfs";
    options = ["subvol=@nixos"];
  };
  fileSystems."/mnt/.btrfs_root_volume" = {
  	    device = "/dev/disk/by-uuid/740e97de-230d-458a-b052-159e5fcfdb75";
		fsType = "btrfs";
		
  };
  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/740e97de-230d-458a-b052-159e5fcfdb75";
    fsType = "btrfs";
    options = ["subvol=@home"];
  };
  
  boot.initrd.luks.devices."luks-4b5f5e00-2fe9-4859-aaa5-f36b40e31e7c".device =
    "/dev/disk/by-uuid/4b5f5e00-2fe9-4859-aaa5-f36b40e31e7c";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/9D3B-2313";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/d1e23c2d-c20d-4240-8ffa-96eca37d39f2"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  # nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  nixpkgs.hostPlatform = {
    system = "x86_64-linux";
  };
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
