# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/b9e924d0-a5ae-42c1-ac7d-1804031b9d3b";
    fsType = "btrfs";
    options = [ "subvol=@nixos" ];
  };
  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/b9e924d0-a5ae-42c1-ac7d-1804031b9d3b";
    fsType = "btrfs";
    options = [ "subvol=@home" ];
  };
  fileSystems."/mnt/hdd" = {
    device = "/dev/disk/by-uuid/11e0a1aa-8a90-4d3d-9b77-6ae641b0818d";
    fsType = "btrfs";
    options = [ "subvol=/" ];
  };
  fileSystems."/mnt/ssd" = {
    device = "/dev/disk/by-uuid/a4ea4565-d4ac-4e08-b5eb-8dbdf5cff838";
    fsType = "btrfs";
    options = [ "subvol=/" ];
  };
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/23E3-386A";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };
  swapDevices = [ { device = "/dev/disk/by-uuid/84ac9096-4679-4047-8434-14bea8363d9e"; } ];

  # nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  nixpkgs.hostPlatform = {
    system = "x86_64-linux";
  };
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
