name: Update-Flake
run-name: Updating NixOS Flake !
permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: "* 2 */14 * *" # every 14 days at 2am
  workflow_dispatch:

jobs:
  Update-Flake:
    runs-on: self-hosted
    steps:
      - run: echo "the server name is $HOSTNAME"
      - run: cat /etc/os-release
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: Create Branch
        uses: peterjgrainger/action-create-branch@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "update-candidate"
      - name: Updating flake
        run: nix flake update .
      - name: Testing nix configuration
        run: nix flake check .
      # - name: GitHub Commit & Push
      #   uses: actions-js/push@v1.5
